config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'
  resources :albums do
    resources :photos
  end
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :album
  has_many_attached :pictures
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  def self.tagged_with(name)
    Tag.find_by!(name: name).photos
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :photos, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :username, uniqueness: true, presence: true
         has_many :albums,    dependent: :destroy
         has_many :photos
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

	before_action :set_album, only: %i[ show edit update destroy ]

  
  def index
   @albums = current_user.albums
  end

  
  def show
  end

 
  def new
    @album = Album.new
  end

 
  def edit
     
  end

  
  def create
    @album = Album.new(album_params)
    @album.user_id = current_user.id
    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:name, :description, :user_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	 before_action :set_photo, only: %i[ show edit]


  def index
    params[:tag] ? @photos = Photo.tagged_with(params[:tag]) : @photos = Photo.all
    album = params[:album_id]
    @photos = current_user.photos.all.where(album_id: album).with_attached_pictures

  end

  
  def show

  end

  
  
  def new
    @photo = Photo.new
  end

  
  def edit
    # @photo = Photo.find(params[:id])
  end

  
  def create
    @photo = Photo.new(photo_params)
    @photo.album_id = params[:album_id]
    @photo.user_id = current_user.id
    # @photo.pictures.attach(params[:photo][:picture])
    respond_to do |format|
      if @photo.save(validate: false)
        format.html { redirect_to album_photos_path , notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @photo = Photo.with_attached_pictures.find(params[:id])
     @photo.user_id = current_user.id
    respond_to do |format|
      if @photo.update(photo_params)
      # raise @photo.inspect
        format.html { redirect_to album_photos_path, notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @photo = Photo.find(params[:id])
    @album = @photo.album_id
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to album_photos_path, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_photo
      @photo = Photo.with_attached_pictures.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:album_id, :user_id, :tag_list, :tag, { tag_ids: [] }, :tag_ids, pictures: [])
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_form.html.erb
<%= simple_form_for(@album) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%#= f.association :user%>
  </div>

  <div class="form-actions">
    <%= f.button :submit ,class:'btn btn-mini btn-warning'%>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>
<%#= render 'photos/form'%>
<%= link_to "Edit Album Phtos", new_album_photo_path(@album.id) %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>




    <%= simple_form_for [@album, @album.photos.build] do |f| %>
   <div class="form-inputs">
    <%= f.text_field :album_id , value: params[:album_id]%> 
    <%= f.label :picture %>
  <%= f.file_field :picture%>
    <%#= f.association :user %>
  </div>
  <%= f.input :album_id, :required => false, :as => :hidden %>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-mini btn-info'%>
  </div>
  <% end %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>
<div class="media">
  <div class="media-body">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"> Action</th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.name %></td>
        <td><%= album.description %></td>
        <td><%= album.user_id %></td>
        <td><%= link_to 'Show', album , class:'btn btn-mini btn-info'%></td>
        <td><%= link_to 'Edit', edit_album_path(album), class:'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>


<br>
<%= link_to 'New Album', new_album_path, class:'btn btn-mini btn-warning' %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %><br>

<%= link_to 'Back', albums_path, class:'btn btn-mini btn-dark' %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>





<div class="card text-center">
  <div class="card-header">
    Album
  </div>
  <div class="card-body">
    <h5 class="card-title bg-warning">Ablum gallary title </h5>
    <p class="card-text">
    <p>
	  <strong>Name:</strong>
	  <%= @album.name %>
	</p>

     <p>
	  <strong>Description:</strong>
	  <%= @album.description %>
	 </p>

	 <p>
	  <strong>User:</strong>
	  <%= @album.user_id %>
	 </p>
    </p>
    <a >
    	<%= link_to 'MY Album list', albums_path , class:'btn btn-mini btn-dark'%>
    </a>
  </div>
  <div class="card-footer text-muted">
    <%= link_to 'Edit', edit_album_path(@album), class:'btn btn-mini btn-success'%> |
	<%= link_to 'Create New Photo', new_album_photo_path(@album), class:'btn btn-primary'%>|
	

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Albumapplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="card">
  <div class="card-header">
     <% if user_signed_in? %>
      <p><%= link_to 'Create Album New', new_album_path ,class:'btn btn-mini btn-primary' %></p> |
      <%= link_to 'Album list', albums_path , class:'btn btn-mini btn-dark'%>|
    <% else %>
      <p><%= link_to 'Register Now', new_user_registration_path , class:'btn btn-mini btn-info'%></p>
    <% end %>

  </div>
  <div class="card-body">
    <h5 class="card-title">
      <li><%= link_to 'Home', root_path, class:'btn btn-mini btn-info' %></li>

    </h5>
    <p class="card-text">
               <% if user_signed_in? %>
                <li><%= link_to "Logout (#{current_user.email})", destroy_user_session_path, :method => :delete ,class:'btn btn-mini btn-danger'%></li>
              <% else %>
    </p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
  
   <li><%= link_to 'Login', new_user_session_path,  class:"btn btn-secondary" %></li>
   <li><%= link_to 'Sign Up', new_user_registration_path,  class:"btn btn-secondary"%></li>
    
  <% end %>
  

app/views/photos/_form.html.erb
<%= simple_form_for [@album, @photo], url: album_photos_path do |form| %>
  <%= form.error_notification %>
  <%= form.error_notification message: form.object.errors[:base].to_sentence if form.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= form.text_field :album_id , value: params[:album_id]%> 
    <%= form.label :picture %>
  <%= form.file_field :pictures, multiple: true%>
    <%#= f.association :user %>
  </div>
  <%= form.input :album_id, :required => false, :as => :hidden %>

  <%= form.label :tag_list, "Tags (separated by commas)" %><br />
  <%= form.text_field :tag_list %>

  <div class="form-actions">
    <%= form.button :submit, class:'btn btn-mini btn-info'%>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= simple_form_for [@album, @photo], url: album_photo_path do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.text_field :album_id , value: params[:album_id]%> 
    <%= f.label :picture %>
  <%= f.file_field :pictures, multiple: true %>
    <%#= f.association :user %>
  </div>
  <%= f.input :album_id, :required => false, :as => :hidden %>
  

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-mini btn-info'%>
  </div><br><br>
<% end %>


<%= link_to 'Show', album_photo_path, class:'btn btn-mini btn-warning'%> |
<%= link_to 'Back', root_path, class:'btn btn-mini btn-dark' %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p><br>

<div class="card-deck">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">
      Card Photos
     </h5>
      <p class="card-text">
      <div class="row">
  <div class="col-sm-8">
      <h1>Photos</h1>
        <div class="media">
          <div class="media-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Album</th>
              <th>User</th>
              <th>Picture</th>
              <th>Tags</th>
              <th colspan="3">Action </th>
            </tr>
          </thead>

          <tbody>
            <% @photos.each do |photo| %>
              <tr>
                <td><%= photo.album_id %></td>
                <td><%= photo.user_id %></td>
                <td><% if photo.pictures.attached? %>
                <% photo.pictures.each do |pic| %>
                <%= image_tag(pic, :class => "pic", style: "height:50px; witdth:50px;") %>
                <% end %>
            <% end %></td>
              <td><small>Tags: <%= raw photo.tags.map(&:name).map { |t| link_to t, root_path(t) }.join(', ') %></small></td>

                <td><%= link_to 'Show', album_photo_path(photo.album_id, photo), class:'btn btn-mini btn-success' %></td>
                <td><%= link_to 'Edit', edit_album_photo_path(photo.album_id, photo), class:'btn btn-mini btn-info'%></td>
                <%#= raise album_id.inspect%>
                <td><%= link_to "Delete", album_photo_path(photo.album_id, photo), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-mini btn-danger' %></td> 
              </tr>
            <% end %>
          </tbody>
        </table>
        </div>
        </div>
        <br>
     <%= link_to 'New Photo', new_album_photo_path, class:'btn btn-mini btn-warning' %>|
      <%= link_to ' home ', root_path, class:'btn btn-mini btn-primary' %> |
      <%= link_to 'Album list', albums_path , class:'btn btn-mini btn-dark'%>|
  </div>
     </p>
      <p class="card-text"><small class="text-muted">
       <%= link_to "Logout (#{current_user.email})", destroy_user_session_path, :method => :delete ,class:'alert alert-success'%>
    </small></p>
    </div>
  </div>
  <div class="card">
    
    <div class="card-body">
      <h5 class="card-title">ALbum Gallary</h5>
      <p class="card-text col-sm-4 btn btn-outline-warning">
        <% @photos.each do |photo| %>
              <% if photo.pictures.attached? %>
                <% photo.pictures.each do |pic| %>
                  <%= image_tag(pic, :class => "pic", style: "height:100px; witdth:100px;") %>
                <% end %>
            <% end %>
        <% end %>
      </p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  
</div>





  

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%#= render 'form', photo: @photo %><br>

<%= link_to 'Back', album_photos_path, class:'btn btn-mini btn-dark' %>

<%= render partial: 'form', photo: @photo, locals: { url: album_photos_path, method: :post} %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album:</strong>
  <%= @photo.album_id %>
</p>

<p>
  <strong>Picture:</strong>
   <% if @photo.pictures.attached? %>
    <% @photo.pictures.each do |pic| %>
    <%= image_tag(pic, :class => "pic") %>
    <% end %>
<% end %>
</p>
  
 
<p>
  <strong>User:</strong>
  <%= @photo.user_id %>
</p>
<%= link_to 'Edit', edit_album_photo_path(@photo) ,class:'btn btn-mini btn-info' %> |
<%= link_to 'Back', album_photos_path, class:'btn btn-mini btn-dark' %>